#yum install vi tar xz wget -y
#docker pull linuxserver/ffmpeg
#goto https://johnvansickle.com/ffmpeg/
#wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz

#tar xf ffmpeg-release-amd64-static.tar.xz

#FROM public.ecr.aws/lambda/python:3.11
FROM amazonlinux:2

# Install necessary packages using yum
RUN yum update -y && \
    yum install -y vi tar xz wget && \
    yum clean all

RUN yum update -y
RUN yum install vi tar xz wget -y
COPY . .
#RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
#RUN tar xf ffmpeg-release-amd64-static.tar.xz
#RUN cp ffmpeg-6.1-amd64-static/ffmpeg /usr/local/bin/

#RUN yum update -y && yum install ffmpeg -y


# Download and install Python 11
RUN yum update -y && \
    yum install -y python3 python3-pip && \
    yum clean all

# Ensure `python` and `pip` are available as commands
RUN ln -s /usr/bin/pip3 /usr/bin/pip

# Verify installations
RUN python --version && pip --version

RUN pip install -r requirements.txt
CMD ["lambda_function.lambda_handler"]


